/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dpsg.conduit.api.models

import dpsg.conduit.api.models.Profile

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param slug 
 * @param title 
 * @param description 
 * @param body 
 * @param tagList 
 * @param createdAt 
 * @param updatedAt 
 * @param favorited 
 * @param favoritesCount 
 * @param author 
 */


data class Article (

    @Json(name = "slug")
    val slug: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "body")
    val body: kotlin.String,

    @Json(name = "tagList")
    val tagList: kotlin.collections.List<kotlin.String>,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "favorited")
    val favorited: kotlin.Boolean,

    @Json(name = "favoritesCount")
    val favoritesCount: kotlin.Int,

    @Json(name = "author")
    val author: Profile

)

