/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dpsg.conduit.api.models

import dpsg.conduit.api.models.Article

import com.squareup.moshi.Json

/**
 * 
 *
 * @param article 
 */


data class CreateArticle201Response (

    @Json(name = "article")
    val article: Article

)

