/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dpsg.conduit.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email 
 * @param password 
 * @param username 
 * @param bio 
 * @param image 
 */


data class UpdateUser (

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "password")
    val password: kotlin.String? = null,

    @Json(name = "username")
    val username: kotlin.String? = null,

    @Json(name = "bio")
    val bio: kotlin.String? = null,

    @Json(name = "image")
    val image: kotlin.String? = null

)

